"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.types import BaseModel


class CreateAPIRequestBodyTypedDict(TypedDict):
    name: str
    r"""The name for your API. This is not customer facing."""


class CreateAPIRequestBody(BaseModel):
    name: str
    r"""The name for your API. This is not customer facing."""


class CreateAPIResponseBodyTypedDict(TypedDict):
    r"""The configuration for an api"""

    api_id: str
    r"""The id of the api"""


class CreateAPIResponseBody(BaseModel):
    r"""The configuration for an api"""

    api_id: Annotated[str, pydantic.Field(alias="apiId")]
    r"""The id of the api"""
