"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.types import BaseModel


class DeleteRoleRequestBodyTypedDict(TypedDict):
    role_id: str
    r"""The id of the role you want to delete."""


class DeleteRoleRequestBody(BaseModel):
    role_id: Annotated[str, pydantic.Field(alias="roleId")]
    r"""The id of the role you want to delete."""


class DeleteRoleResponseBodyTypedDict(TypedDict):
    r"""Sucessfully deleted a role"""


class DeleteRoleResponseBody(BaseModel):
    r"""Sucessfully deleted a role"""
