"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from typing_extensions import Annotated, TypedDict
from unkey.types import BaseModel


class DeletePermissionRequestBodyTypedDict(TypedDict):
    permission_id: str
    r"""The id of the permission you want to delete."""


class DeletePermissionRequestBody(BaseModel):
    permission_id: Annotated[str, pydantic.Field(alias="permissionId")]
    r"""The id of the permission you want to delete."""


class DeletePermissionResponseBodyTypedDict(TypedDict):
    r"""Sucessfully deleted a permission"""


class DeletePermissionResponseBody(BaseModel):
    r"""Sucessfully deleted a permission"""
