"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unkey.types import BaseModel


class ListPermissionsResponseBodyTypedDict(TypedDict):
    id: str
    r"""The id of the permission"""
    name: str
    r"""The name of the permission."""
    description: NotRequired[str]
    r"""The description of what this permission does. This is just for your team, your users will not see this."""


class ListPermissionsResponseBody(BaseModel):
    id: str
    r"""The id of the permission"""

    name: str
    r"""The name of the permission."""

    description: Optional[str] = None
    r"""The description of what this permission does. This is just for your team, your users will not see this."""
